name: arderas_flutter_packages # Arderas Flutter Packages
repository: https://github.com/ardera/flutter_packages
packages:
  - packages/**
  - examples/**

command:
  version:
    # Generate commit links in package changelogs.
    linkToCommits: true
    # Only allow versioning to happen on main branch.
    branch: main
    # Additionally build a changelog at the root of the workspace.
    workspaceChangelog: true
  bootstrap:
    usePubspecOverrides: true

scripts:
  pubget:
    run: |
      melos exec -- \
        flutter pub get
    description:
      Run `flutter pub get` in all packages.
  
  generate:
    run: melos run generate:dart && melos run generate:flutter
    description: Build all generated files for Dart & Flutter packages in this project.

  generate:dart:
    run: melos exec -c 1 --depends-on="build_runner" --no-flutter -- "dart run build_runner build --delete-conflicting-outputs"
    description: Build all generated files for Dart packages in this project.

  generate:flutter:
    run: melos exec -c 1 --depends-on="build_runner" --flutter -- "flutter pub run build_runner build --delete-conflicting-outputs"
    description: Build all generated files for Flutter packages in this project.

  test:
    run: melos run test:dart --no-select && melos run test:flutter --no-select
    description: Run all Dart & Flutter tests in this project.

  test:dart:
    run: melos exec -c 1 --fail-fast -- dart test
    description: Run `dart test` in all pure-dart packages with a `test` folder.
    packageFilters:
      flutter: false
      dirExists: test

  test:flutter:
    run: melos exec -c 1 --fail-fast -- flutter test
    description: Run `flutter test` in all flutter packages with a `test` folder.
    packageFilters:
      flutter: true
      dirExists: test

  checkformat:
    run: melos exec -c 1 "dart format --line-length=120 --output=none --set-exit-if-changed ."
    description: Check all packages are formatted.

  format:
    run: melos exec -c 1 "dart format --line-length=120 ."
    description: Format all packages.

  analyze:
    run: melos run analyze:dart --no-select && melos run analyze:flutter --no-select
    description: Analyze all flutter and dart packages.

  analyze:dart:
    run: melos exec -c 1 "dart analyze --fatal-infos ."
    description: Run `dart analyze --fatal-infos` in all pure-dart packages.
    packageFilters:
      flutter: false

  analyze:flutter:
    run: melos exec -c 1 "flutter analyze --fatal-infos ."
    description: Run `flutter analyze --fatal-infos` in all flutter packages.
    packageFilters:
      flutter: true
  
  checkpubpoints:
    run: melos exec -c 1 "cp -r "