targets:
  $default:
    builders:
      _ardera_libc_bindings_generator|libc_platform_binding_gen:
        generate_for:
          - lib/src/libc_arm.dart
          - lib/src/libc_arm64.dart
          - lib/src/libc_i386.dart
          - lib/src/libc_amd64.dart
        options:
          distro: sid
          windowsLlvmPath: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\Llvm\\x64\\"
          sevenZipCommand: "C:\\Program Files\\7-Zip\\7z.exe"
          ffigen-options:
            headers:
              entry-points:
                - 'errno.h'
                - 'fcntl.h'
                - 'unistd.h'
                - 'sys/ioctl.h'
                - 'sys/types.h'
                - 'sys/stat.h'
                - 'sys/epoll.h'

                # flutter_gpiod
                - 'linux/gpio.h'

                # linux_serial
                - 'termios.h'

                # linux_spidev
                - 'linux/spi/spidev.h'

            functions:
              include:
                - ioctl
                - epoll_create
                - epoll_create1
                - epoll_ctl
                - epoll_wait
                - __errno_location
                - open
                - close
                - read

                # linux_serial
                - cfgetispeed
                - cfgetospeed
                - cfsetispeed
                - cfsetospeed
                - tcdrain
                - tcflow
                - tcflush
                - tcgetattr
                - tcgetsid
                - tcsendbreak
                - tcsetattr
              rename:
                '__errno_location': 'errno_location'
              symbol-address:
                include:
                  - epoll_ctl
                  - epoll_wait
                  - __errno_location
                  - read
                  - ioctl
              leaf:
                include:
                  - '.*'
            structs:
              include:

                # flutter_gpiod
                - gpiochip_info
                - gpio_v2_line_values
                - gpio_v2_line_attribute
                - gpio_v2_line_config_attribute
                - gpio_v2_line_config
                - gpio_v2_line_request
                - gpio_v2_line_info
                - gpio_v2_line_info_changes
                - gpio_v2_line_event
                - gpioline_info
                - gpioline_info_changed
                - gpiohandle_request
                - gpiohandle_config
                - gpiohandle_data
                - gpioevent_request
                - gpioevent_data

                # linux_serial
                - termios

                # linux_spidev
                - spi_ioc_transfer
              exclude:
                # currently doesn't work because of packing issues
                # we supply our own epoll_event & epoll_data
                - epoll_event
                - epoll_data
              dependency-only: opaque
            unions:
              include:
                - epoll_data
            enums:
              include:
                - 'EPOLL_EVENTS'
            unnamed-enums: 
              include:
                - 'EPOLL.*'
                - 'O_.*'
                - 'GPIO.*'
            globals:
              exclude:
                - '.*'
            typedefs:
              include: []
            macros:
              include:
                # open flags
                - 'O_.*'
                # errno error codes & EPOLL operations
                - 'E.*'

                # flutter_gpiod
                - 'GPIO.*'

                # linux_serial
                # termios structure
                # array subscripts for termios c_cc
                - 'NCCS'
                - 'VEOF'
                - 'VEOL'
                - 'VINTR'
                - 'VKILL'
                - 'VQUIT'
                - 'VSTART'
                - 'VSTOP'
                - 'VSUSP'
                - 'VTIME'
                - 'VMIN'
                # input modes
                # termios c_iflag
                - 'BRKINT'
                - 'ICRNL'
                - 'INLCR'
                - 'IGNBRK'
                - 'IGNCR'
                - 'IGNPAR'
                - 'INPCK'
                - 'ISTRIP'
                - 'IXANY'
                - 'IXOFF'
                - 'IXON'
                - 'PARMRK'
                # output modes
                # termios c_oflag
                - 'OPOST'
                - 'ONLCR'
                - 'OCRNL'
                - 'ONOCR'
                - 'ONLRET'
                - 'OFDEL'
                - 'OFILL'
                - 'NLDLY'
                - 'NL0'
                - 'NL1'
                - 'CRDLY'
                - 'CR0'
                - 'CR1'
                - 'CR2'
                - 'CR3'
                - 'TABDLY'
                - 'TAB0'
                - 'TAB1'
                - 'TAB2'
                - 'TAB3'
                - 'BSDLY'
                - 'BS0'
                - 'BS1'
                - 'VTDLY'
                - 'VT0'
                - 'VT1'
                - 'FFDLY'
                - 'FF0'
                - 'FF1'
                # baud rate selection
                - 'B[0-9]+'
                # control modes
                # termios c_cflag
                - 'CSIZE'
                - 'CS[0-9]'
                - 'CSTOPB'
                - 'CREAD'
                - 'PARENB'
                - 'PARODD'
                - 'HUPCL'
                - 'CLOCAL'
                # local modes
                # termios c_lflag
                - 'ECHO'
                - 'ECHOE'
                - 'ECHOK'
                - 'ECHONL'
                - 'ICANON'
                - 'IEXTEN'
                - 'ISIG'
                - 'NOFLSH'
                - 'TOSTOP'
                # attribute selection
                # tcsetattr
                - 'TCSANOW'
                - 'TCSADRAIN'
                - 'TCSAFLUSH'
                # line control
                # tcflush
                - 'TCIFLUSH'
                - 'TCIOFLUSH'
                - 'TCOFLUSH'
                # tcflow
                - 'TCIOFF'
                - 'TCION'
                - 'TCOOFF'
                - 'TCOON'
                
                # linux_spidev
                - 'SPI_CPHA'
                - 'SPI_CPOL'
                - 'SPI_MODE_0'
                - 'SPI_MODE_1'
                - 'SPI_MODE_2'
                - 'SPI_MODE_3'
                - 'SPI_MODE_X_MASK'
                - 'SPI_CS_HIGH'
                - 'SPI_LSB_FIRST'
                - 'SPI_3WIRE'
                - 'SPI_LOOP'
                - 'SPI_NO_CS'
                - 'SPI_READY'
                - 'SPI_TX_DUAL'
                - 'SPI_TX_QUAD'
                - 'SPI_RX_DUAL'
                - 'SPI_RX_QUAD'
                - 'SPI_CS_WORD'
                - 'SPI_TX_OCTAL'
                - 'SPI_RX_OCTAL'
                - 'SPI_3WIRE_HIZ'
                - 'SPI_MSGSIZE'
                - 'SPI_IOC_MAGIC'
                - 'SPI_IOC_MESSAGE'
                - 'SPI_IOC_RD_MODE'
                - 'SPI_IOC_WR_MODE'
                - 'SPI_IOC_RD_LSB_FIRST'
                - 'SPI_IOC_WR_LSB_FIRST'
                - 'SPI_IOC_RD_BITS_PER_WORD'
                - 'SPI_IOC_WR_BITS_PER_WORD'
                - 'SPI_IOC_RD_MAX_SPEED_HZ'
                - 'SPI_IOC_WR_MAX_SPEED_HZ'
                - 'SPI_IOC_RD_MODE32'
                - 'SPI_IOC_WR_MODE32'
              exclude:
                # somehow these have different values depending on ABI.
                - 'O_NOFOLLOW'
                - 'O_DIRECTORY'
