name: linux_serial
description: Dart package for accessing serial ports on Linux using dart:ffi.
version: 0.1.0
homepage: https://ardera.dev
repository: https://github.com/ardera/flutter_packages

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  ffi: ^2.0.0
  meta: ^1.3.0
  tuple: ^2.0.0
  path: ^1.8.0
  async: ^2.5.0
  computer: ^3.2.1
  synchronized: ^3.0.0
  _ardera_common_libc_bindings: ^0.0.1
